---
- name: Adicionando PPA do php 5.6
  apt_repository:
    validate_certs: no
    repo: 'ppa:ondrej/php'
    state: present
- name: Install PHP Depedency
  apt: 
    name: ['php5.6', 'php5.6-fpm', 'php5.6-mysql', 'php', 'php-bz2', 'php-curl', 'php-gd', 'php-mbstring', 'php-gettext', 'php-zip', 'php5.6-zip', 'php-tcpdf', 'php-xml', 'phpmyadmin', 'php-dev', 'libmcrypt-dev', 'gcc', 'make', 'autoconf', 'libc-dev', 'pkg-config']
    update_cache: yes
    state: present
  become_method: sudo
  become: yes
- name: Update module mcrypt part 1
  shell: pecl install mcrypt-1.0.1
  become_method: sudo
  become: yes
- name: Update module mcrypt part 2
  shell: echo "extension=mcrypt.so" | sudo tee -a /etc/php/5.6/apache2/conf.d/mcrypt.ini
  become_method: sudo
  become: yes

