---
- include: install-phpmain.yml

- name: enable php-fpm
  shell: a2enmod actions proxy_fcgi && a2enmod php5.6 && a2enmod proxy_http && a2enmod ssl
  notify:
   - restart apache2
  become: true
  become_user: root
